name: Create and Push File

on:
  push:
    branches:
      - ouproj_template

jobs:
  create-and-push-file:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Create file
        run: touch test.txt

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b test_gha
          git add .
          git commit -m "Add test.txt"
          git push origin test_gha
