name: mirrortest

on:
  push:
    branches:
      - ouproj_template

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Mirror repository
      run: |
        git clone --mirror https://github.com/rmgpanw/ourproj
        cd ourproj.git
        git push --mirror https://github.com/rmgpanw/ourproj_template_minimal.git
