name: mirrortest

on:
  push:
    branches:
      - ouproj_template

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: ouproj_template

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install dependencies
        run: |
          rm renv.lock
          rm -r renv
          rm .Rprofile
          R -e 'install.packages("remotes", repos = "https://cloud.r-project.org")'
          while read -r cmd
          do
            eval sudo $cmd
          done < <(Rscript -e 'writeLines(remotes::system_requirements("ubuntu", "20.04"))')
          R -e 'install.packages("devtools", repos = "https://cloud.r-project.org")'
          R -e 'library(devtools); install_deps()'

      - name: Create template repo in separate directory
        run: |
          R -e 'devtools::install_local(".")'
          R -e 'library(ourproj); ourproj_start(directory = "~/ourproj_template_minimal", project_title = "My Project", git_username = "rmgpanw", github_gitlab = "github")'

      - name: Create new branch with template repo, commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout --orphan test_gha
          git reset
          rm -rf .[^.]* *
          cp -r ~/ourproj_template_minimal/. .
          git add .
          git commit -m "Initial commit"
          git push --force origin ourproj_template_minimal

      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "rmgpanw/ourproj"
          source_branch: "ourproj_template_minimal"
          destination_repo: "rmgpanw/ourproj_template_minimal"
          destination_branch: "master"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional
          # source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
          # destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
