name: mirrortest

on:
  push:
    branches:
      - ouproj_template

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: ouproj_template

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install dependencies
        run: |
          R -e 'install.packages("devtools", repos = "https://cloud.r-project.org")'
          R -e 'library(devtools); install_deps()'

      - name: Create template repo in separate directory
        run: |
          R -e 'library(pkgname); ourproj_start(directory = "~/ourproj_template_minimal", project_title = "My Project", git_username = "rmgpanw", github_gitlab = "github")'

      - name: Create new branch with template repo, commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout --orphan test_gha
          git reset
          rm -r *
          cp -r ~/ourproj_template_minimal .
          git add .
          git commit -m "Add test.txt"
          git push --force origin test_gha

      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "rmgpanw/ourproj"
          source_branch: "test_gha"
          destination_repo: "rmgpanw/ourproj_template_minimal"
          destination_branch: "main"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional
          # source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
          # destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
