name: mirrortest

on:
  push:
    branches:
      - ouproj_template

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Mirror repository
      run: |

        echo "SET UP SSH KEY"
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/gh_actions_key
        chmod 600 ~/.ssh/gh_actions_key

        # see https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/
        ssh-keygen -R github.com
        curl -L https://api.github.com/meta | jq -r '.ssh_keys | .[]' | sed -e 's/^/github.com /' >> ~/.ssh/known_hosts

        echo "LIST FILES"
        ls -lah

        pwd

        cd inst/ourproj_template_minimal

        pwd

        echo "INITIATE GIT REPO"
        git init

        echo "set git config"
        git config --local user.name "rmgpanw"
        git config --local user.email "${{ secrets.GIT_USER_EMAIL }}"

        echo "list files in dir"
        ls -lah

        echo "add files and commit"
        git add .
        git commit -m "initial commit"
        git branch -M main

        echo "add remote origin"
        git remote add origin git@github.com:rmgpanw/ourproj_template_minimal.git

        echo "push to destination repo"
        git push -u origin main
