name: mirrortest

on:
  push:
    branches:
      - ouproj_template

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Create and remove files, commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b test_gha
          touch test.txt && rm _template_repo_dependencies.R
          git add .
          git commit -m "Add test.txt"
          git push --force origin test_gha

      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "rmgpanw/ourproj"
          source_branch: "ouproj_template"
          destination_repo: "rmgpanw/ourproj_template_minimal"
          destination_branch: "main"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional
          # source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
          # destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
